#!/usr/bin/env python3
"""Generate a deterministic low-poly dark-fantasy tree OBJ for voxel-displacement E2E tests."""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from pathlib import Path


Vec3 = tuple[float, float, float]


def add(a: Vec3, b: Vec3) -> Vec3:
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def sub(a: Vec3, b: Vec3) -> Vec3:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def scale(a: Vec3, value: float) -> Vec3:
    return (a[0] * value, a[1] * value, a[2] * value)


def dot(a: Vec3, b: Vec3) -> float:
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a: Vec3, b: Vec3) -> Vec3:
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def normalise(value: Vec3) -> Vec3:
    length = math.sqrt(dot(value, value)) or 1.0
    return scale(value, 1.0 / length)


@dataclass
class ObjWriter:
    vertices: list[Vec3]
    uvs: list[tuple[float, float]]
    normals: list[Vec3]
    faces: list[tuple[str, tuple[tuple[int, int, int], ...]]]

    @classmethod
    def create(cls) -> "ObjWriter":
        return cls([], [], [], [])

    def vertex(self, position: Vec3, uv: tuple[float, float], normal: Vec3) -> tuple[int, int, int]:
        self.vertices.append(position)
        self.uvs.append(uv)
        self.normals.append(normalise(normal))
        return (len(self.vertices), len(self.uvs), len(self.normals))

    def face(self, material: str, corners: tuple[tuple[int, int, int], ...]) -> None:
        self.faces.append((material, corners))

    def write(self, path: Path) -> None:
        lines = ["# Generated by generate_low_poly_tree_obj.py", "o DarkFantasyTree", "s off"]
        lines.extend(f"v {x:.8f} {y:.8f} {z:.8f}" for x, y, z in self.vertices)
        lines.extend(f"vt {u:.8f} {v:.8f}" for u, v in self.uvs)
        lines.extend(f"vn {x:.8f} {y:.8f} {z:.8f}" for x, y, z in self.normals)
        active = None
        for material, corners in self.faces:
            if material != active:
                lines.append(f"usemtl {material}")
                active = material
            lines.append("f " + " ".join(f"{v}/{uv}/{n}" for v, uv, n in corners))
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def add_frustum(writer: ObjWriter, start: Vec3, end: Vec3, start_radius: float, end_radius: float, material: str, sides: int = 7) -> None:
    direction = normalise(sub(end, start))
    reference = (0.0, 1.0, 0.0) if abs(direction[1]) < 0.9 else (1.0, 0.0, 0.0)
    basis_u = normalise(cross(direction, reference))
    basis_v = normalise(cross(direction, basis_u))
    rings: list[list[tuple[int, int, int]]] = []
    for center, radius, longitudinal in ((start, start_radius, 0.0), (end, end_radius, 1.0)):
        ring = []
        for side in range(sides):
            angle = (2.0 * math.pi * side) / sides
            radial = add(scale(basis_u, math.cos(angle)), scale(basis_v, math.sin(angle)))
            ring.append(writer.vertex(add(center, scale(radial, radius)), (side / sides, longitudinal), radial))
        rings.append(ring)
    for side in range(sides):
        nxt = (side + 1) % sides
        writer.face(material, (rings[0][side], rings[0][nxt], rings[1][nxt]))
        writer.face(material, (rings[0][side], rings[1][nxt], rings[1][side]))
    cap_start = writer.vertex(start, (0.5, 0.0), scale(direction, -1.0))
    cap_end = writer.vertex(end, (0.5, 1.0), direction)
    for side in range(sides):
        nxt = (side + 1) % sides
        writer.face(material, (cap_start, rings[0][nxt], rings[0][side]))
        writer.face(material, (cap_end, rings[1][side], rings[1][nxt]))


def add_ellipsoid(writer: ObjWriter, center: Vec3, radii: Vec3, material: str, segments: int = 7, rings: int = 3) -> None:
    if segments < 3 or rings < 2:
        raise ValueError("ellipsoid needs at least three segments and two rings")
    bottom_unit = (0.0, -1.0, 0.0)
    top_unit = (0.0, 1.0, 0.0)
    bottom = writer.vertex(add(center, (0.0, -radii[1], 0.0)), (0.5, 0.0), bottom_unit)
    rows: list[list[tuple[int, int, int]]] = []
    for row in range(1, rings):
        phi = -math.pi * 0.5 + math.pi * row / rings
        row_vertices = []
        for segment in range(segments):
            theta = 2.0 * math.pi * segment / segments
            unit = (math.cos(phi) * math.cos(theta), math.sin(phi), math.cos(phi) * math.sin(theta))
            position = add(center, (unit[0] * radii[0], unit[1] * radii[1], unit[2] * radii[2]))
            row_vertices.append(writer.vertex(position, (segment / segments, row / rings), unit))
        rows.append(row_vertices)
    top = writer.vertex(add(center, (0.0, radii[1], 0.0)), (0.5, 1.0), top_unit)
    for segment in range(segments):
        nxt = (segment + 1) % segments
        writer.face(material, (bottom, rows[0][nxt], rows[0][segment]))
    for row in range(len(rows) - 1):
        for segment in range(segments):
            nxt = (segment + 1) % segments
            writer.face(material, (rows[row][segment], rows[row + 1][segment], rows[row + 1][nxt]))
            writer.face(material, (rows[row][segment], rows[row + 1][nxt], rows[row][nxt]))
    for segment in range(segments):
        nxt = (segment + 1) % segments
        writer.face(material, (top, rows[-1][segment], rows[-1][nxt]))


def add_diamond(writer: ObjWriter, center: Vec3, width: float, height: float, depth: float, material: str) -> None:
    front = center[2] - depth * 0.5
    back = center[2] + depth * 0.5
    points = [
        (center[0], center[1] + height * 0.5),
        (center[0] + width * 0.5, center[1]),
        (center[0], center[1] - height * 0.5),
        (center[0] - width * 0.5, center[1]),
    ]
    front_ring = [writer.vertex((x, y, front), (index / 4, 1.0), (0.0, 0.0, -1.0)) for index, (x, y) in enumerate(points)]
    back_ring = [writer.vertex((x, y, back), (index / 4, 0.0), (0.0, 0.0, 1.0)) for index, (x, y) in enumerate(points)]
    writer.face(material, (front_ring[0], front_ring[1], front_ring[2], front_ring[3]))
    writer.face(material, (back_ring[3], back_ring[2], back_ring[1], back_ring[0]))
    for index in range(4):
        nxt = (index + 1) % 4
        writer.face(material, (front_ring[index], back_ring[index], back_ring[nxt], front_ring[nxt]))


def build_tree() -> ObjWriter:
    writer = ObjWriter.create()
    bark = "bark"
    leaf = "leaf"
    moss = "moss"
    rune = "rune"

    segments: list[tuple[Vec3, Vec3, float, float]] = [
        ((0.0, 0.0, 0.0), (0.0, 1.8, 0.0), 1.0, 0.78),
        ((0.0, 1.4, 0.0), (-0.25, 3.2, 0.03), 0.78, 0.53),
        ((-0.25, 3.0, 0.03), (-0.75, 4.7, 0.0), 0.54, 0.33),
        ((-0.75, 4.65, 0.0), (-1.35, 5.9, 0.08), 0.34, 0.17),
        ((-1.35, 5.85, 0.08), (-1.25, 6.85, 0.1), 0.18, 0.06),
        ((-0.2, 2.8, 0.0), (0.2, 4.2, 0.05), 0.5, 0.3),
        ((0.2, 4.15, 0.05), (0.1, 5.65, 0.1), 0.3, 0.14),
        ((0.1, 5.6, 0.1), (0.65, 6.55, 0.08), 0.15, 0.05),
        ((0.0, 1.6, 0.05), (-1.15, 2.35, 0.12), 0.67, 0.4),
        ((-1.1, 2.35, 0.12), (-2.35, 2.75, 0.05), 0.41, 0.22),
        ((-2.3, 2.72, 0.05), (-3.2, 3.55, 0.0), 0.23, 0.07),
        ((0.0, 1.7, -0.05), (1.2, 2.4, -0.12), 0.67, 0.39),
        ((1.15, 2.4, -0.12), (2.35, 2.95, -0.18), 0.4, 0.2),
        ((2.3, 2.95, -0.18), (3.2, 3.75, -0.12), 0.21, 0.06),
        ((-0.15, 2.2, 0.45), (-1.4, 3.4, 0.75), 0.45, 0.23),
        ((-1.35, 3.4, 0.75), (-2.2, 4.45, 0.8), 0.24, 0.07),
        ((0.15, 2.4, -0.55), (1.3, 3.55, -0.9), 0.43, 0.22),
        ((1.25, 3.55, -0.9), (2.25, 4.5, -0.95), 0.23, 0.06),
        ((-0.15, 3.5, 0.0), (-0.95, 4.9, -0.85), 0.32, 0.13),
        ((-0.95, 4.9, -0.85), (-1.25, 6.05, -0.9), 0.14, 0.05),
        ((0.1, 3.5, 0.0), (1.0, 4.8, 0.65), 0.34, 0.14),
        ((1.0, 4.8, 0.65), (1.45, 5.9, 0.7), 0.15, 0.05),
    ]
    for start, end, start_radius, end_radius in segments:
        add_frustum(writer, start, end, start_radius, end_radius, bark)

    roots = [
        ((0.0, 0.15, 0.0), (2.4, -0.1, 0.1)),
        ((0.0, 0.12, 0.0), (-2.45, -0.1, 0.1)),
        ((0.0, 0.1, 0.0), (0.5, -0.08, 2.35)),
        ((0.0, 0.1, 0.0), (-0.65, -0.1, -2.4)),
        ((0.0, 0.1, 0.0), (1.85, -0.1, -1.4)),
        ((0.0, 0.1, 0.0), (-1.85, -0.1, 1.55)),
    ]
    for start, end in roots:
        add_frustum(writer, start, end, 0.55, 0.08, bark, sides=7)

    leaves = [
        (-1.25, 6.95, 0.1), (0.65, 6.68, 0.08), (-2.2, 4.55, 0.8), (1.45, 6.0, 0.7),
        (-3.25, 3.65, 0.0), (3.25, 3.85, -0.12), (2.25, 4.55, -0.95),
        (-2.4, 2.85, 0.05), (2.4, 3.0, -0.18), (-1.0, 5.0, -0.85),
    ]
    for index, position in enumerate(leaves):
        add_ellipsoid(writer, position, (0.45 + (index % 3) * 0.05, 0.22, 0.32), leaf)

    moss_patches = [
        (-0.45, 1.35, -0.65), (-0.85, 3.45, -0.45), (0.45, 2.35, 0.55),
        (1.3, 3.65, -0.8), (-1.35, 2.35, 0.1), (0.8, 4.75, 0.55),
        (-0.6, 0.45, 0.8), (1.55, 0.05, -1.0),
    ]
    for position in moss_patches:
        add_ellipsoid(writer, position, (0.28, 0.12, 0.18), moss, segments=6, rings=2)

    add_diamond(writer, (-0.22, 2.05, -0.79), 0.28, 0.5, 0.05, rune)
    add_diamond(writer, (0.28, 2.55, -0.78), 0.25, 0.42, 0.05, rune)
    return writer


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    build_tree().write(args.out.expanduser().resolve())
    print(args.out.expanduser().resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
